language: objective-c
xcode_workspace: Tests/CocoaLUTTests.xcworkspace
xcode_scheme: CocoaLUTTests
before_install:
  - gem install cocoapods -v '0.32.1' --no-rdoc --no-ri
  - pod repo remove master
  - pod setup
install:
  - cd Tests
  - pod install
  - cd ..
